import { Player } from "./player.js";
import { InputHandler } from "./input.js";
import { Background } from "./background.js";
import { FlyingEnemy, ClimbingEnemy, GroundEnemy } from "./enemies.js";
import { UI } from "./UI.js"; //how do we update architecture when changing file names? it doesnt recognize
//rip audio
const bgAudio = new Audio("./assets/audio/background-music.ogg");

// Ensure the audio loops continuously
bgAudio.loop = true;
//restart button
const restartButton = document.getElementById("restart-button");

// Restart Button Logic
restartButton.addEventListener("click", () => {
  location.reload(); // Reloads the page
});

// Handle music button click
const musicButton = document.getElementById("music-button");
musicButton.addEventListener("click", () => {
  if (bgAudio.paused) {
    bgAudio.play();
    musicButton.textContent = "🎵 Music is Playing... 🎵";
  } else {
    bgAudio.pause();
    musicButton.textContent = "🎵 Summon the Music 🎵";
  }
});

// Prevent "Enter" key from triggering the button
musicButton.addEventListener("keydown", (event) => {
  if (event.key === "Enter") {
    event.preventDefault(); // Prevent default behavior
  }
});
//
/* Wrapper to make sure stylesheet and images are loaded
before running the script */
window.addEventListener("load", function () {
  const canvas = document.getElementById("canvas1");
  const ctx = canvas.getContext("2d");
  canvas.width = 900;
  canvas.height = 500;

  /*   this.document.addEventListener("mousemove", () => {
    setTimeout(() => {
      bgAudio.play();
    }, 2500);
  });
 */
  class Game {
    constructor(width, height) {
      this.width = width;
      this.height = height;
      //margin for player character
      this.groundMargin = 80;
      //game speed for layers
      this.speed = 0;
      //global speed setting
      this.maxSpeed = 3;
      this.background = new Background(this);
      this.player = new Player(this);
      this.input = new InputHandler(this);
      this.UI = new UI(this);
      //helpers for enemy spawn
      this.enemies = []; //holds all active enemies in an array
      this.particles = []; //hold particles
      this.collisions = []; //hold collision animation objects
      this.floatingMessages = [];
      this.enemyTimer = 0; //increases by deltaTime everytime it
      // reaches a value in enemyinterval we create a new enemy and reset to 0
      this.enemyInterval = 1000;
      this.debug = false; //press d
      this.score = 0;
      this.winningScore = 40;
      this.fontColor = "black";

      //time limit
      this.time = 0;
      this.maxTime = 30000;
      this.gameOver = false;
      //
      this.lives = 5;
      this.player.currentState = this.player.states[0];
      //when player object is created activate its initial default state
      this.player.currentState.enter();

      this.maxParticles = 100;
    }
    //run for every animation frame
    update(deltaTime) {
      //time limit
      this.time += deltaTime;
      if (this.time > this.maxTime) this.gameOver = true;
      //
      this.background.update();
      this.player.update(this.input.keys, deltaTime);
      //handle enemies
      if (this.enemyTimer > this.enemyInterval) {
        this.addEnemy();
        this.enemyTimer = 0;
      } else {
        this.enemyTimer += deltaTime;
      }
      this.enemies.forEach((enemy) => {
        enemy.update(deltaTime);
      });
      //handle Messages
      this.floatingMessages.forEach((message) => {
        message.update();
      });
      //handle particles       . foreach method passes autogenerated index argument so i can just assign it
      this.particles.forEach((particle, index) => {
        //call update method for each particle held in array
        particle.update();
        if (particle.markedForDeletion) this.particles.splice(index, 1);
      });
      //limit particles to 50
      if (this.particles.length > this.maxParticles) {
        this.particles.length = this.maxParticles;
        // this.particles = this.particles.slice(0, 50);
      }
      //console.log(this.particles);

      //handle collision sprites
      this.collisions.forEach((collision, index) => {
        collision.update(deltaTime);
        if (collision.markedForDeletion) this.collisions.splice(index, 1);
      });
      //*its bad to cycle through the same array once in update and once in draw method
      this.enemies = this.enemies.filter(
        //override
        (enemy) => !enemy.markedForDeletion
      );
      //filter floating messages array
      this.floatingMessages = this.floatingMessages.filter(
        //override
        (message) => !message.markedForDeletion
      );
    }
    //draw our images/score etc
    draw(context) {
      this.background.draw(context);
      this.player.draw(context);
      this.enemies.forEach((enemy) => {
        enemy.draw(context);
      });
      this.particles.forEach((particle) => {
        particle.draw(context);
      });
      this.collisions.forEach((collision) => {
        collision.draw(context);
      });
      this.floatingMessages.forEach((message) => {
        message.draw(context);
      });
      this.UI.draw(context);
    }
    //add enemies at intervals
    addEnemy() {
      //only spawn enemies when we are moving and not every 1000ms (50%)
      if (this.speed > 0 && Math.random() < 0.5)
        this.enemies.push(new GroundEnemy(this));
      else if (this.speed > 0) this.enemies.push(new ClimbingEnemy(this));
      this.enemies.push(new FlyingEnemy(this));
      console.log(this.enemies);
    }
  }
  const game = new Game(canvas.width, canvas.height);
  console.log(game);

  //helper variable DeltaTime to calculate Frames of Spritesheet
  let lastTime = 0;

  //animation loop for 60 fps
  function animate(timeStamp) {
    const deltaTime = timeStamp - lastTime;
    //console.log(deltaTime);
    lastTime = timeStamp;
    //clear old paint => only see current animation (whole canvas from to)
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    game.update(deltaTime);
    game.draw(ctx);
    //this thing gives back timestamps aswell to calculate deltaTime
    if (!game.gameOver) requestAnimationFrame(animate);
  }
  animate(0); //0 is so important because first value of deltaTime is a NaN so we have to serve a first value (0)
});
